### ISSUE TITLE
Interactive widget first click on the widget without refreshing

### ISSUE THREAD

**Issue by hyzhan43** [ABausG/home_widget#254]
in iOS widgets When I used home_widgets for interaction, I found that the first time I opened the app and clicked the widget button, the widget interface would not refresh

But the actual data has been updated, and the backgroundCallback has also been called back. After clicking on the widget, it will refresh normally.

And I am https://github.com/ABausG/home_widget_counter Also reproduced this situation, is this a bug?

**Comment by armandsLa** [comment]
@hyzhan43 please look at this PR. I had a similar issue and this fix helped me:
https://github.com/ABausG/home_widget/pull/244

**Comment by hyzhan43** [comment]
I tried to make some modifications, but the problem still exists

**Comment by armandsLa** [comment]
I have created a fork with this fix applied. You can try it by updating your pubspec:
```
  home_widget:
    git:
      url: https://github.com/armandsLa/home_widget.git
      ref: fix-ios-worker
```
